name: Build tikz-builder image
on:
  push:
    branches: [v4]
    paths:
      - '.github/images/tikz-builder/**'
      - '.github/workflows/image-tikz.yml'
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v7
        with:
          context: .github/images/tikz-builder
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/tikz-builder:latest
            ghcr.io/${{ github.repository_owner }}/tikz-builder:${{ github.sha }}